package rs.rbt.jobrunrrbt.helper

const val DATE_TIME_STYLE: String = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'"
const val JOBRUNR_JOBS_TABLE_NAME: String = "jobrunr_jobs"
const val ID: String = "id"
const val VERSION: String = "version"
const val JOB_AS_JSON: String = "jobasjson"
const val JOB_SIGNATURE: String = "jobsignature"
const val STATE: String = "state"
const val CREATED_AT: String = "createdat"
const val UPDATED_AT: String = "updatedat"
const val SCHEDULED_AT: String = "scheduledat"
const val RECURRING_JOB_ID: String = "recurringjobid"
const val JOBRUNR_RECURRING_JOBS_TABLE_NAME: String = "jobrunr_recurring_jobs"
const val OBJECT: String = "object"
const val AT_CLASS: String = "@class"
const val OFFSET:String = "offset"
const val LIMIT:String = "limit"
const val ORDER:String = "order"
const val SEARCH_PARAMETER:String = "searchParameter"
const val SEARCH_VALUE:String = "searchValue"
const val CLASS:String = "Class"
const val METHOD:String = "Method"
const val PACKAGE_NAME:String = "packageName"
const val METHOD_NAME:String = "methodName"
const val CLASS_NAME: String = "className"
const val SCHEDULED_TIME:String = "scheduledTime"
