package rs.rbt.jobrunrrbt.helper

const val DATE_TIME_STYLE: String = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'"
const val JOBRUNR_JOBS_TABLE_NAME: String = "jobrunr_jobs"
const val ID: String = "id"
const val VERSION: String = "version"
const val JOBASJSON: String = "jobasjson"
const val JOBSIGNATURE: String = "jobsignature"
const val STATE: String = "state"
const val CREATEDAT: String = "createdat"
const val UPDATEDAT: String = "updatedat"
const val SCHEDULETAT: String = "scheduledat"
const val RECCURINGJOBID: String = "recurringjobid"
const val JOBRUNR_RECURRING_JOBS_TABLE_NAME: String = "jobrunr_recurring_jobs"
const val OBJECT: String = "object"
const val AT_CLASS: String = "@class"
const val FIND_JOBS_BY_CLASS_AND_METHOD:String = "\"\"\"select j from JobrunrJob j where j.state = ?1 and j.jobsignature like concat('%', ?2, '%', '(', '%')\"\"\""
const val FIND_JOBS_BY_CLASS: String = "\"\"\"select * from jobrunr_jobs where state =?1 and jobsignature ~ ?2\"\"\", nativeQuery = true"
const val FIND_JOBS_BY_METHOD: String = "\"\"\"select * from jobrunr_jobs where state =?1 and jobsignature ~ ?2\"\"\", nativeQuery = true"
const val COUNT_JOBS_BY_CLASS_AND_METHOD: String = "\"\"\"select count(j) from JobrunrJob j where j.state = ?1 and j.jobsignature like concat('%', ?2, '%', '(', '%')\"\"\""
const val COUNT_JOBS_BY_CLASS: String = "\"\"\"select count (*) from jobrunr_jobs j where j.state =?1 and j.jobsignature ~ ?2\"\"\", nativeQuery = true"
const val COUNT_JOBS_BY_METHOD: String = "\"\"\"select count (*) from jobrunr_jobs j where j.state =?1 and j.jobsignature ~ ?2\"\"\", nativeQuery = true"
const val UPDATE_SIGNATURE: String = "\"update JobrunrJob set jobsignature = ?2 where id = ?1\""
const val UPDATE_JOBASJSON:String = "\"update JobrunrJob set jobasjson = ?2 where id = ?1\""
const val UPDATE_SCHEDULED_TIME:String = "\"update JobrunrJob set scheduledat = ?2 where id = ?1\""
const val OFFSET:String = "offset"
const val LIMIT:String = "limit"
const val ORDER:String = "order"
const val SEARCH_PARAMETER:String = "searchParameter"
const val SEARCH_VALUE:String = "searchValue"
const val CLASS:String = "Class"
const val METHOD:String = "Method"
const val PACKAGE_NAME:String = "packageName"
const val METHOD_NAME:String = "methodName"
const val CLASS_NAME: String = "className"
const val SCHEDULED_TIME:String = "scheduledTime"
