version: '3.0'

services:
  db:
    image: 'postgres'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=JobRunrRBT
  jobrunr-service:
    image: 'jobrunr'
    container_name: jobrunr
    build: ./
    depends_on:
      - db
    ports:
      - "8000:8000"
  jobrunr-dashboard:
    image: 'dashboard'
    container_name: dashboard
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - db
      - jobrunr-service
    ports:
      - "3000:3000"